# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-10 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termsandconditions', '0003_auto_20170627_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsandconditions',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, b'Sitewide Ts and Cs'), (10, b'Data Export Pages only')], default=0),
        ),
    ]
